import '@/styles/globals.css'
import Nav from '@/app/components/Nav'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import Hydrate from './components/Hydrate'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await getServerSession(authOptions)
	return (
		<html lang="en">
			<Hydrate>
				<Nav user={session?.user} />
				{children}
			</Hydrate>
		</html>
	)
}
