import '@/styles/globals.css'
import Nav from '@/components/Nav'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await getServerSession(authOptions)
	return (
		<html lang="en">
			<body className="mx-64 bg-slate-950	">
				<Nav user={session?.user} />
				{children}
			</body>
		</html>
	)
}
